#!/bin/bash

lock_file() {
  if [ ! -f ${1} ]; then 
    echo "${1} does not exist."
    return
  fi

  openssl enc -aes-256-cbc -a -salt -in "${1}" -out "${1}".enc
  if [ $? -eq 0 ]; then
    rm $1
  fi
}

unlock_file() {
  if [ ! -f ${1}.enc ]; then 
    echo "${1}.enc does not exist."
    return
  fi

  openssl enc -d -aes-256-cbc -a -in "${1}".enc -out "${1}"
  if [ $? -eq 0 ]; then
    rm $1.enc
  fi
}

lock() {
  for i in $@
  do
    echo "Locking ${i}"
    lock_file ${i}
  done
}

unlock() {
  for i in $@
  do
    echo "Unlocking ${i}"
    unlock_file ${i}
  done
}

# main

min=2 
if [ $# -lt "$min" ]; then
  echo "Too few arguments"
  exit 1
fi

case ${1} in
  lock   ) $@ ;;
  unlock ) $@ ;;
  *      ) echo "Unrecognized subcommand: ${1}";;
esac
